USE [master]
GO
/****** Object:  Database [CofeeShop]    Script Date: 27.02.2026 07:47:49 PM ******/
CREATE DATABASE [CofeeShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CofeeShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\CofeeShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CofeeShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\CofeeShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [CofeeShop] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CofeeShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CofeeShop] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CofeeShop] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CofeeShop] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CofeeShop] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CofeeShop] SET ARITHABORT OFF 
GO
ALTER DATABASE [CofeeShop] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CofeeShop] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CofeeShop] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CofeeShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CofeeShop] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CofeeShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CofeeShop] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CofeeShop] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CofeeShop] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CofeeShop] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CofeeShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CofeeShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CofeeShop] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CofeeShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CofeeShop] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CofeeShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CofeeShop] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CofeeShop] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CofeeShop] SET  MULTI_USER 
GO
ALTER DATABASE [CofeeShop] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CofeeShop] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CofeeShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CofeeShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CofeeShop] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CofeeShop] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [CofeeShop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [CofeeShop] SET QUERY_STORE = ON
GO
ALTER DATABASE [CofeeShop] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [CofeeShop]
GO
/****** Object:  Table [dbo].[Adresses]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Adresses](
	[AdressID] [int] IDENTITY(1,1) NOT NULL,
	[city] [varchar](50) NOT NULL,
	[country] [varchar](50) NOT NULL,
	[street] [varchar](50) NOT NULL,
	[street_number] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Adresses] PRIMARY KEY CLUSTERED 
(
	[AdressID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Baristas]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Baristas](
	[BaristaID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[salary] [money] NOT NULL,
	[id_CofeeShopID] [int] NOT NULL,
 CONSTRAINT [PK_Baristas] PRIMARY KEY CLUSTERED 
(
	[BaristaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Beverages]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Beverages](
	[BeverageID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[details] [varchar](500) NULL,
 CONSTRAINT [PK_Beverages] PRIMARY KEY CLUSTERED 
(
	[BeverageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Beverages_Sizes]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Beverages_Sizes](
	[Beverages_SizesID] [int] IDENTITY(1,1) NOT NULL,
	[id_BeverageID] [int] NOT NULL,
	[id_SizeID] [int] NOT NULL,
	[price] [money] NOT NULL,
 CONSTRAINT [PK_Beverages_Sizes] PRIMARY KEY CLUSTERED 
(
	[Beverages_SizesID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CofeeShops]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CofeeShops](
	[CofeeShopID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[id_AdressID] [int] NOT NULL,
	[manager_name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CofeeShops] PRIMARY KEY CLUSTERED 
(
	[CofeeShopID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[email] [varchar](15) NOT NULL,
	[loyal_points] [money] NOT NULL,
	[id_MemberID] [int] NOT NULL,
	[pasword] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Extras]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Extras](
	[ExtrasID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[price] [money] NOT NULL,
 CONSTRAINT [PK_Extras] PRIMARY KEY CLUSTERED 
(
	[ExtrasID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Extras_Items]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Extras_Items](
	[Extras_ItemsID] [int] IDENTITY(1,1) NOT NULL,
	[id_ExtrasID] [int] NOT NULL,
	[id_ItemsID] [int] NOT NULL,
	[current_price] [money] NOT NULL,
 CONSTRAINT [PK_Extras_Beverages] PRIMARY KEY CLUSTERED 
(
	[Extras_ItemsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Items]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Items](
	[ItemsID] [int] IDENTITY(1,1) NOT NULL,
	[id_TransactionID] [int] NOT NULL,
	[id_Beverages_SizesID] [int] NOT NULL,
	[current_price] [money] NOT NULL,
 CONSTRAINT [PK_Items] PRIMARY KEY CLUSTERED 
(
	[ItemsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Membership_Types]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Membership_Types](
	[MemberID] [int] IDENTITY(1,1) NOT NULL,
	[type] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Membership_Types] PRIMARY KEY CLUSTERED 
(
	[MemberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sizes]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sizes](
	[SizeID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](10) NOT NULL,
	[details] [varchar](500) NULL,
 CONSTRAINT [PK_Sizes] PRIMARY KEY CLUSTERED 
(
	[SizeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transactions]    Script Date: 27.02.2026 07:47:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transactions](
	[TransactionID] [int] IDENTITY(1,1) NOT NULL,
	[id_CostomerID] [int] NOT NULL,
	[id_BaristaID] [int] NOT NULL,
	[total_price] [money] NOT NULL,
	[nr_loyal_points] [money] NOT NULL,
	[date] [datetime] NOT NULL,
 CONSTRAINT [PK_Transactions] PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Baristas]  WITH CHECK ADD  CONSTRAINT [FK_Baristas_CofeeShops] FOREIGN KEY([id_CofeeShopID])
REFERENCES [dbo].[CofeeShops] ([CofeeShopID])
GO
ALTER TABLE [dbo].[Baristas] CHECK CONSTRAINT [FK_Baristas_CofeeShops]
GO
ALTER TABLE [dbo].[Beverages_Sizes]  WITH CHECK ADD  CONSTRAINT [FK_Beverages_Sizes_Beverages] FOREIGN KEY([id_BeverageID])
REFERENCES [dbo].[Beverages] ([BeverageID])
GO
ALTER TABLE [dbo].[Beverages_Sizes] CHECK CONSTRAINT [FK_Beverages_Sizes_Beverages]
GO
ALTER TABLE [dbo].[Beverages_Sizes]  WITH CHECK ADD  CONSTRAINT [FK_Beverages_Sizes_Sizes] FOREIGN KEY([id_SizeID])
REFERENCES [dbo].[Sizes] ([SizeID])
GO
ALTER TABLE [dbo].[Beverages_Sizes] CHECK CONSTRAINT [FK_Beverages_Sizes_Sizes]
GO
ALTER TABLE [dbo].[CofeeShops]  WITH CHECK ADD  CONSTRAINT [FK_CofeeShops_Adresses] FOREIGN KEY([id_AdressID])
REFERENCES [dbo].[Adresses] ([AdressID])
GO
ALTER TABLE [dbo].[CofeeShops] CHECK CONSTRAINT [FK_CofeeShops_Adresses]
GO
ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Customers_Membership_Types] FOREIGN KEY([id_MemberID])
REFERENCES [dbo].[Membership_Types] ([MemberID])
GO
ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_Membership_Types]
GO
ALTER TABLE [dbo].[Extras_Items]  WITH CHECK ADD  CONSTRAINT [FK_Extras_Items_Extras] FOREIGN KEY([id_ExtrasID])
REFERENCES [dbo].[Extras] ([ExtrasID])
GO
ALTER TABLE [dbo].[Extras_Items] CHECK CONSTRAINT [FK_Extras_Items_Extras]
GO
ALTER TABLE [dbo].[Extras_Items]  WITH CHECK ADD  CONSTRAINT [FK_Extras_Items_Items] FOREIGN KEY([id_ItemsID])
REFERENCES [dbo].[Items] ([ItemsID])
GO
ALTER TABLE [dbo].[Extras_Items] CHECK CONSTRAINT [FK_Extras_Items_Items]
GO
ALTER TABLE [dbo].[Items]  WITH CHECK ADD  CONSTRAINT [FK_Items_Beverages_Sizes] FOREIGN KEY([id_Beverages_SizesID])
REFERENCES [dbo].[Beverages_Sizes] ([Beverages_SizesID])
GO
ALTER TABLE [dbo].[Items] CHECK CONSTRAINT [FK_Items_Beverages_Sizes]
GO
ALTER TABLE [dbo].[Items]  WITH CHECK ADD  CONSTRAINT [FK_Items_Transactions] FOREIGN KEY([id_TransactionID])
REFERENCES [dbo].[Transactions] ([TransactionID])
GO
ALTER TABLE [dbo].[Items] CHECK CONSTRAINT [FK_Items_Transactions]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK_Transactions_Baristas] FOREIGN KEY([id_BaristaID])
REFERENCES [dbo].[Baristas] ([BaristaID])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK_Transactions_Baristas]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK_Transactions_Customers] FOREIGN KEY([id_CostomerID])
REFERENCES [dbo].[Customers] ([CustomerID])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK_Transactions_Customers]
GO
USE [master]
GO
ALTER DATABASE [CofeeShop] SET  READ_WRITE 
GO
